app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'index', 'uses' => 'MainController@getIndex']);

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
	'my' => 'HomeController',
	'lang' => 'LangController',
	'/' => 'MainController'
]);

app/Models/User.php
<?php namespace RockAffinity\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends Model implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'facebook_id', 'email', 'password', 'status', 'role', 'picture', 'about_me', 'short_str'];

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];

	public function getProfilePictureAttribute()
	{
		return substr($this->picture, 0,4) === 'http' ? $this->picture : asset("image/team/{$this->picture}");
	}

	/**
	 * Formated about_me
	 *
	 * @return string
	 */
	public function getAboutAttribute()
	{
		$lines = explode(PHP_EOL, $this->about_me);

		foreach ( $lines as &$line )
		{
			if ( ! $line )
				unset($line);

			else if ( $line[0] === '*' )
				$line = '<h4>'.substr($line, 1).'</h4>';
		}
		return implode(PHP_EOL, $lines);
	}
}

app/Http/Controllers/MainController.php
<?php namespace RockAffinity\Http\Controllers;

use Session;
use Illuminate\Http\Request;
use RockAffinity\Models\Video;
use RockAffinity\Repositories\MainRepository as Repository;
use RockAffinity\Models\User;
use RockAffinity\Models\Event;

class MainController extends Controller {

	/*
	|--------------------------------------------------------------------------
	| Welcome Controller
	|--------------------------------------------------------------------------
	|
	| This controller renders the "marketing page" for the application and
	| is configured to only allow guests. Like most of the other sample
	| controllers, you are free to modify or remove it as you desire.
	|
	*/

	protected $layout = 'layout.main';

	protected $main;

	/**
	 * Create a new controller instance.
	 *
	 * @return void
	 */
	public function __construct(Repository $repository)
	{
		$this->main = $repository;
	}

	/**
	 * Show the application welcome screen to the user.
	 *
	 * @return Response
	 */
	public function getIndex()
	{
		return $this->view('page.posts',[
			'posts' => $this->main->lastPosts(),
			'event' => $this->main->nextEvent(),
		]);
	}

	public function getEvents()
	{
		$events = $this->main->lastEvents();

		return $this->view('page.events',[
			'eventsJson' => with(new \RockAffinity\Repositories\EventRepository)->jsonify($events)
		]);
	}

	public function getEventList()
	{
		$events = $this->main->lastEvents();
		return $this->view('page.eventList',[
			'events' => $this->main->lastEvents(),
		]);
	}

	public function getRocker($member)
	{
		if ( $user = User::where('short_str',$member)->first() )
			return $this->view('page.rocker',[
				'user' => $user
			]);

		abort(404);
	}

	public function postRocker($member,Request $request)
	{
		if ( ($user = User::where('short_str',$member)->first()) && $user->email && \Validator::make($request->all(),[
			'message' => 'required'])->passes() )
		{
				\Mail::queue('emails.simple',[
				'data' => $request->input('message')
				],function($message) use($user){
				$message->to($user->email)->subject('RockAffinity website - contact');
			});

			return response()->success($user->email,'messages.contactSent');
		}
	}

	public function getContact()
	{
		return $this->view('page.contact');
	}

	public function postContact(Request $request)
	{
		$validator = $this->main->contactValidator($request->all());

		if ( $validator->fails() )
		{
			$this->throwValidationException(
				$request, $validator
			);
		}

		$this->main->sendContactMail($request->all());

		return redirect(action('MainController@getContact'))
			->with('messages.valids',[
				trans('messages.contactSent')
			]);
	}

	public function getPartners()
	{
		return $this->view('page.partners');
	}

	public function getVideos()
	{
		return $this->view('page.videos',[
			'videos' => Video::all()
			]);
	}

	public function getPhotos($id = null)
	{
		if ( ! $id )
			return $this->view('page.albums',[
				'albums' => $this->main->getFacebookAlbums()
			]);

		else
			return $this->view('page.photos',[
				'album' => $this->main->getFacebookAlbum($id)
			]);
	}

	public function getAssociation()
	{
		$this->layout = 'layout.full';

		return $this->view('page.association',[
			'users' => \RockAffinity\Models\User::all()
			]);
	}

	public function getPlaylists()
	{
		return $this->view('page.playlists',[
			'playlists' => \RockAffinity\Models\Playlist::all()
			]);
	}

	public function getYourSong()
	{
		return $this->view('page.tracks',[
			'tracks' => \RockAffinity\Models\Track::all()
			]);
	}

	public function getPlaylist($id = null,$name = null)
	{
		if ( ! ( $playlist = \RockAffinity\Models\Playlist::find($id) ) )
			return redirect(route('index'));

		return $this->view('page.playlist',[
			'playlist' => $playlist
			]);
	}

	public function getVoteSong($id)
	{
		if ( Session::has('vote') )
			return redirect(route('index'))->with('messages.valids',[
				'You have voted already!']);

		$t = \RockAffinity\Models\Track::find($id);

		$t->likes = $t->likes + 1;

		$t->save();

		Session::put('vote',true);

		return redirect(route('index'))->with('messages.valids',[
			'Thanks for voting!']);
	}

	/**
	 * Isolated event.
	 *
	 * @param int $id
	 * @param string $slug
	 * @return \Illuminate\Http\Response
	 */
	public function getEvent($id,$slug = null)
	{
		if ( ! ($event = Event::find($id)) )
			return redirect(route('index'));

		if ( ($real_slug = str_slug($event->name)) !== $slug )
			return redirect(action('MainController@getEvent',[$id,$real_slug]));

		return $this->view('event.wide',[
			'event' => $event
			]);
	}

	public function getTest(Request $request)
	{
		throw new \Illuminate\Http\Exception\HttpResponseException(response()->error('invalidQuery'));
	}

}

resources/views/page/association.blade.php
@section('page')
<div class="ra_img_cont">
	<img src="{{asset('image/team.jpeg')}}" class="img-responsive" alt="" style="border:10px dotted #000"/>
	<a href="{{action('MainController@getRocker','etienne')}}" class="ra_member_on_image" style="top:105px;left:654px"></a>
	<a href="{{action('MainController@getRocker','andrea')}}" class="ra_member_on_image" style="top:160px;left:570px"></a>
	<a href="{{action('MainController@getRocker','mohammed')}}" class="ra_member_on_image" style="top:180px;left:310px"></a>
	<a href="{{action('MainController@getRocker','bernard')}}" class="ra_member_on_image" style="top:160px;left:510px"></a>
	<a href="{{action('MainController@getRocker','stephane')}}" class="ra_member_on_image" style="top:110px;left:350px"></a>
	<a href="{{action('MainController@getRocker','marie')}}" class="ra_member_on_image" style="top:180px;left:380px"></a>
	<a href="{{action('MainController@getRocker','amine')}}" class="ra_member_on_image" style="top:140px;left:750px"></a>
	<a href="{{action('MainController@getRocker','flavien')}}" class="ra_member_on_image" style="top:164px;left:208px"></a>
	<a href="{{action('MainController@getRocker','colombine')}}" class="ra_member_on_image" style="top:170px;left:450px"></a>
</div>
<p class="lead">{{utrans('association.team')}}</p>
<div class="row">
@foreach ( $users as $user )
	<div class="col-md-4" style="margin-bottom:5px">
		<a href="{{action('MainController@getRocker',$user->short_str)}}" class="ra_member_text">
		<div class="media">
			<div class="media-left">
					<img class="media-object" style="width:64px;height:64px" src="{{$user->profile_picture}}" alt="" />
			</div>
			<div class="media-body">
				<h4 class="media-heading">{{$user->name}}</h4>
					{{utrans("role.{$user->role}")}}
			</div>
		</div>
		</a>
	</div>
@endforeach
</div>
<hr />
<p class="lead">{{utrans('association.title.who')}}</p>
<div class="row">
		<div class="col-md-3">
			<img class="img-responsive" src="{{asset('image/what.png')}}" alt="" />
		</div>
		<div class="col-md-9">
@foreach ( trans('association.text.who') as $item )
			<p>{{ucfirst($item)}}</p>
@endforeach
		</div>
</div>
<hr />
<p class="lead">{{utrans('association.title.why')}}</p>
<div class="row">
		<div class="col-md-9">
@foreach ( trans('association.text.why') as $item )
			<p>{{ucfirst($item)}}</p>
@endforeach
		</div>
		<div class="col-md-3">
			<img class="img-responsive" src="{{asset('image/guy.png')}}" alt="" />
		</div>
</div>
<hr />
<p class="lead">{{utrans('association.title.for')}}</p>
<div class="row">
		<div class="col-md-3">
			<img class="img-responsive" src="{{asset('image/girl.png')}}" alt="" />
		</div>
		<div class="col-md-9">
@foreach ( trans('association.text.for') as $item )
			<p>{{ucfirst($item)}}</p>
@endforeach
		</div>
</div>
<hr />
@stop

resources/views/page/contact.blade.php
@section('page')
<p class="lead">{{utrans('contact.where')}}</p>

<iframe style="width:100%;border:0" height="300" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA6KyHsATuHdj2ufLXz8P5q03OOcaBeqR8&q=Tacos%20Bar%20Lausanne"></iframe>

<p class="lead">{{utrans('contact.contact')}}</p>
<div class="row">
	<div class="col-md-8 col-sm-8 col-xs-12">
		<form action="{{action('MainController@postContact')}}" method="post" accept-charset="utf-8" class="form-horizontal cm_contact_form">
			<div class="form-group">
				<label for="" class="col-md-3 control-label">{{utrans('contact.name')}}<sup>*</sup></label>
				<div class="col-md-9">
				<input type="text" class="form-control" name="name" value="" required autofocus />
				</div>
			</div>
			<div class="form-group">
				<label for="" class="col-md-3 control-label">{{utrans('contact.email')}}<sup>*</sup></label>
				<div class="col-md-9">
				<input type="email" class="form-control" name="email" value="" required />
				</div>
			</div>
			<div class="form-group">
				<label for="" class="col-md-3 control-label">{{utrans('contact.object')}}</label>
				<div class="col-md-9">
				<input type="text" class="form-control" name="phone" value="" />
				</div>
			</div>

			<div class="form-group">
				<label for="" class="col-md-3 control-label">{{utrans('contact.message')}}<sup>*</sup></label>
				<div class="col-md-9">
				<textarea type="text" class="form-control" name="message" value="" required style="resize:vertical"></textarea>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-9 col-md-offset-3">
					<input type="hidden" name="_token" value="{{csrf_token()}}">
					<button type="submit" class="btn btn-primary">{{utrans('contact.send')}}</button>
				</div>
			</div>
		</form>
	</div>
</div>

@stop

resources/views/page/dashboard.blade.php
@section('page')
<p class="lead">{{utrans('main.feedback')}}</p>
<ul>
	<li><a href="{{action('HomeController@getMostLikedSongs')}}">{{utrans('main.mostLikedSongs')}}</a></li>
</ul>
<p class="lead">{{utrans('main.manageProfile')}}</p>
<ul>
	<li><a href="{{action('HomeController@getProfile')}}">{{utrans('user.profile')}}</a></li>
</ul>
<p class="lead">{{utrans('main.manageContent')}}</p>
<ul>
	<li><a href="{{action('HomeController@getEdit','post')}}">{{utrans('main.posts')}}</a></li>
	<li><a href="{{action('HomeController@getEdit','event')}}">{{utrans('main.events')}}</a></li>
	<li><a href="{{action('HomeController@getCore')}}">{{utrans('main.updateBase')}}</a></li>
</ul>
@stop

resources/views/page/eventList.blade.php
@section('page')

<p class="lead">{{utrans('event.list')}} <a href="{{action('MainController@getEvents')}}" class="pull-right">{{utrans('event.calendar')}}</a></p>

@foreach ( $events as $event )
@include('event.inList')
<hr />
@endforeach
@stop

resources/views/page/events.blade.php
@section('page')

<p class="lead">{{utrans('event.calendar')}}<a href="{{action('MainController@getEventList')}}" class="pull-right">{{utrans('event.list')}}</a></p>

{{utrans('event.chooseMonth')}}
<div class="btn-group btn-group-sm">
	<button href="#" class="btn btn-default" data-calendar-nav="prev">{{utrans('event.prevC')}}</button>
	{{--<button class="btn" data-calendar-nav="today">Today</button>--}}
	<a href="#" class="btn btn-primary"><span id="ra_cal_title"></span></a>
	<button class="btn btn-default" data-calendar-nav="next">{{utrans('event.nextC')}}</button>
</div>

<div id="ra_calendar"></div>

<div id="ra_calendar_data" class="hidden">
{!!$eventsJson!!}
</div>

@stop

resources/views/page/mostLikedSongs.blade.php
@section('page')
<p class="lead">On Spotify:</p>
@foreach($spotifySongs as $song)
	{{$song->title}} - {{$song->popularity}}<br />
@endforeach
<p class="lead">User liked:</p>
@foreach($likedSongs as $song)
	{{$song->title}} - {{$song->likes}}<br />
@endforeach
@stop

resources/views/page/partners.blade.php
@section('page')
@foreach ( Config::get('partners.list',[]) as $key => $partner )
<p class="lead">{{$partner['name']}}</p>
<div class="row">
	@if ( $key % 2 )
		<div class="col-xs-3">
			<a href="{{$partner['link']}}"><img class="img-responsive" src="{{asset('image/sp/'.$partner['img'])}}" alt="" /></a>
		</div>
		<div class="col-xs-9">
			<p>{{utrans($partner['desc'])}}</p>
			<p><a href="{{$partner['link']}}">{{utrans('partner.site')}}</a></p>
		</div>
	@else
		<div class="col-xs-9">
			<p>{{utrans($partner['desc'])}}</p>
			<p><a href="{{$partner['link']}}">{{utrans('partner.site')}}</a></p>
		</div>
		<div class="col-xs-3">
			<a href="{{$partner['link']}}"><img class="img-responsive" src="{{asset('image/sp/'.$partner['img'])}}" alt="" /></a>
		</div>
	@endif
</div>
<hr />
@endforeach
@stop

resources/views/page/photos.blade.php
@section('page')
<p class="lead">{{$album['name']}}<a href="{{action('MainController@getPhotos')}}" class="pull-right">{{utrans('album.list')}}</a></p>
<div class="row">
@foreach ( $album['data'] as $photo )
	<div class="col-xs-6" style="text-align:center;margin-bottom:10px">
			<img class="img-responsive" src="http://graph.facebook.com/{{$photo->id}}/picture" alt="" />
	</div>
@endforeach
</div>
@stop

resources/views/page/playlist.blade.php
@section('page')
<p class="lead">{{$playlist->name}}<a href="{{action('MainController@getPlaylists')}}" class="pull-right">{{utrans('playlist.backToList')}}</a></p>
<div class="row">
@foreach ( $playlist->tracks as $track )
	<div class="col-sm-3 col-xs-6" style="text-align:center;">
		<a href="{{$track->link}}">
			<span class="text-align:center">
@for ( $i=0; $i < $track->hearts ; $i ++ )
<span class="glyphicon glyphicon-heart"></span>
@endfor
			</span><br />
			<img src="{{$track->cover}}" alt="" class="img-thumbnail" style="height:100px;width:100px" />
			<p style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{$track->title}} - {{$track->artist}}</p>
		</a>
	</div>
@endforeach
</div>
@stop

resources/views/page/playlists.blade.php
@section('page')
<p class="lead">{{utrans('playlist.list')}}</p>
<div class="row">
@foreach ( $playlists as $playlist )
	<div class="col-sm-3 col-xs-6" style="text-align:center;">
		<a href="{{action('MainController@getPlaylist',$playlist->id)}}">
			<img src="{{$playlist->cover}}" alt="" class="img-thumbnail" style="height:100px;width:100px" />
			<p style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{$playlist->name}}</p>
		</a>
	</div>
@endforeach
</div>
@stop

resources/views/page/posts.blade.php
@section('page')

<h1>{{utrans('event.next')}}</h1>
<div class="alert alert-danger">
@if ($event)
	@include('event.inList')
@endif
</div>
<hr />
@foreach ( $posts as $post )
<div class="media">
	<div class="media-left">
		<img class="media-object ra_post_picture" src="{{$post->picture}}" alt="">
  </div>
  <div class="media-body">
    <h4 class="media-heading">{{$post->title}}</h4>
    {!!$post->message!!}
  </div>
</div>
<hr />
@endforeach
@stop

resources/views/page/profile.blade.php
@section('page')

<p class="lead">{{utrans('user.profile')}}</p>
<form class="form-horizontal ra_profile_edit" data-id="{{$user->id}}">
@foreach ( Config::get('user.editables',[]) as $name )
	<div class="form-group">
		<label for="ra_edit_{{$name}}" class="col-sm-2 control-label">{{utrans("user.$name")}}</label>
		<div class="col-sm-10">
	@if ( Config::has("user.inputType.$name") )
		@if ( Config::get("user.inputType.$name") === 'textarea' )
			<textarea name="{{$name}}" class="form-control" data-name="{{$name}}" id="ra_edit_{{$name}}">{{$user->$name}}</textarea>
		@endif
	@else
			<input type="text" class="form-control" id="ra_edit_{{$name}}" data-name="{{$name}}" value="{{$user->$name}}" />
	@endif
		</div>
	</div>
@endforeach
</form>
@stop

resources/views/page/rocker.blade.php
@section('page')
<p class="lead">{{$user->name}} : {{utrans("role.{$user->role}")}}</p>
	<div class="col-md-6 pull-right">
		<img src="{{asset($user->picture)}}" alt="" class="img-responsive" style="border:10px dotted #000" />
	</div>
{!!$user->about!!}

@if ( $user->email )
	<br />
	<button class="btn btn-primary pull-right" data-toggle="modal" data-target="#ra_contactM"><span class="glyphicon glyphicon-envelope"></span> {{utrans('user.contactMe')}}</button>
	<div class="modal fade" id="ra_contactM" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title" id="ra_contactM_label"><span class="glyphicon glyphicon-envelope"></span> {{utrans('user.contactMe')}}</h4>
				</div>
				<div class="modal-body">
					<textarea name="message" class="form-control" id="ra_contact_msg"></textarea>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" id="ra_contact_me">{{utrans('user.contactMe')}}</button>
				</div>
			</div>
		</div>
	</div>
@endif
<hr />
<a href="{{action('MainController@getAssociation')}}" class="lead"><span class="glyphicon glyphicon-plus"></span> {{utrans('association.team')}}</a>
@stop

resources/views/page/tracks.blade.php
@section('page')
<p class="lead">{{utrans('playlist.yourSong')}}</p>
<div class="row">
@foreach ( $tracks as $track )
	<div class="col-sm-3 col-xs-6" style="text-align:center;">
@if ( ! Session::has('vote') )
		<a href="{{action('MainController@getVoteSong',$track->id)}}">
@endif
			<span class="text-align:center">
@for ( $i=0; $i < $track->hearts ; $i ++ )
<span class="glyphicon glyphicon-heart"></span>
@endfor
			</span><br />
			<img src="{{$track->cover}}" alt="" class="img-thumbnail" style="height:100px;width:100px" />
			<p style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">{{$track->title}} - {{$track->artist}}</p>
@if ( ! Session::has('vote') )
		</a>
@endif
	</div>
@endforeach
</div>
@stop