app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', ['as' => 'index', 'uses' => 'MainController@getIndex']);

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
	'my' => 'HomeController',
	'lang' => 'LangController',
	'/' => 'MainController'
]);

app/Models/Event.php
<?php namespace RockAffinity\Models;

use Carbon\Carbon;

class Event extends Model
{

	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['facebook_id', 'google_id', 'name', 'start_time', 'end_time', 'location', 'picture', 'description', 'link', 'people_going'];

	public function getTimeAttribute()
	{
		$c_start = Carbon::parse($this->start_time);
		$c_end = Carbon::parse($this->end_time);

		if ( $c_start->dayOfWeek === $c_end->dayOfWeek)
			return trans('event.time1',[
				'fday' => utrans("event.day.{$c_start->dayOfWeek}"),
				'day' => $c_start->format('j'),
				'month' => utrans("event.month.{$c_start->format('n')}"),
				'start' => $c_start->format('H:i'),
				'end' => $c_end->format('H:i')]);

		else
			return trans('event.time1',[
				'fday' => utrans("event.day.{$c_start->dayOfWeek}"),
				'day' => $c_start->format('j'),
				'month' => utrans("event.month.{$c_start->format('n')}"),
				'start' => $c_start->format('H:i'),
				'end' => $c_end->format('H:i')]);
	}

}

resources/views/event/inList.blade.php
<div id="event-{{$event->id}}" class="ra_hash"></div>
<p class="lead">{{$event->name}} <span class="pull-right">{{$event->time}}</span></p>
<div class="row">
	<div class="col-md-4">
		<iframe style="width:100%;border:0" height="200" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA6KyHsATuHdj2ufLXz8P5q03OOcaBeqR8&q={{urlencode($event->location)}}"></iframe>
	</div>
	<div class="col-md-8" style="max-height:250px;overflow:hidden;text-overflow:ellipsis">
		{!!nl2br($event->description)!!}
	</div>
</div>

resources/views/event/wide.blade.php
@section('page')
<div id="event-{{$event->id}}" class="ra_hash"></div><p class="lead">{{$event->name}} <span class="pull-right">{{$event->time}}</span></p>
<div class="row">
	<div class="col-md-4">
		<iframe style="width:100%;border:0" height="200" frameborder="0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA6KyHsATuHdj2ufLXz8P5q03OOcaBeqR8&q={{urlencode($event->location)}}"></iframe>
	</div>
	<div class="col-md-8" style="max-height:250px;overflow:hidden;text-overflow:ellipsis">
		{!!nl2br($event->description)!!}
	</div>
</div>
<img src="{{$event->picture}}" alt="" class="img-responsive" />

@stop